spring:
  application:
    name: myAccountService
  profiles:
    active: dev

---
spring:
  config:
    activate.on-profile: dev
  sql.init.mode: always
  datasource:
    url: "jdbc:h2:mem:accounts_db"
    driverClassName: org.h2.Driver
    username: demo_user
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

logging:
  level:
    root: DEBUG
  file.path: /var/logs
  file.name: /var/logs/accounts.log

server:
  port: 9900
---
spring:
  config:
    activate.on-profile: prod

  sql.init.mode: never
  datasource:
    url: "jdbc:mysql://localhost/productos_db"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: productos_user
    password: prod123

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    hibernate:
      ddl-auto: update
      generate-ddl: false
    defer-datasource-initialization: false

logging:
  level:
    root: ERROR


server:
  port: 9943
  servlet:
    context-path: "/api/v1"
